### PR TITLE
Fix: default to StandardChecker for TP.checkers

### PR DESCRIPTION
**Pull request by phlax**

### CODE REVIEW

**Comment by unho** [comment]
A brief explanation of our journey through the rabbit hole might help, isn't it?

**Comment by ta2-1** [comment]
merge it faster!

**Comment by unho** [comment]
A possible explanation:

The absence of 'standard' key in translate.filters.check.projectcheckers (fixed in https://github.com/translate/translate/commit/87a5e3db) caused projects with 'standard' checkstyle to default to `StandardUnitChecker` (4 checks) instead of `StandardChecker` (dozens of checks) thus rendering it useless.

**Comment by unho** [comment]
lgtm

**Pull request merged**
