### PR TITLE
TM results: hide context if unavailable

### LINKED ISSUE #3541: Local TM UI doesn't work for amaGama results
We should integrate local TM and amaGama results. Local TM has access to other information such as the project name and person who translated the suggestion since it has access to the data from Pootle.

When using amaGama results the string in the UI is confusing: 

*Translated by someone in project ""*

screen shot 2015-01-23 at 17 55 13

We should either:

1. Include some of that information in amaGama results e.g. the project name
2. Use a different comment when we have results from amaGama e.g. just remove it

### PR DESCRIPTION
**Pull request by julen**
Please test and report @jleclanche @dwaynebailey.

Fixes #3541.

### CODE REVIEW

**Comment by jleclanche** [comment]
Thanks, will test.

**Comment by jleclanche** [comment]
Seems to work fine, gtm

**Comment by dwaynebailey** [comment]
lgtm.  The message is certainly gone in my results which are from amaGama.  I'll assume the local TM side works.

**Comment by jleclanche** [comment]
@dwaynebailey codacy is sure being annoying. I dont think we should enable it until we're actually clean...

**Comment by dwaynebailey** [comment]
@jleclanche yeah, I've had to message them as I can't seem to disable it.  Can't actually recall enabling it  in fact either.

**Comment by julen** [comment]
I disabled the webhook for the time being; it's just being useless noise.

**Pull request merged**
