### PR TITLE
Removing pot files from stats

### LINKED ISSUE #3245: POT files counted into Need Translation
In statistics, string from POT files appears as "Need Translation" and therefore breaks stats about translation completeness

Pootle 2.6.0-rc1 (Django 1.12.0-rc1, Translate Toolkit 1.6.5)

### PR DESCRIPTION
**Pull request by phlax**
When calculating wordcount stats don't include .pot template files

fixes #3245

as requested by @jleclanche - the process i followed was:

- looked at main project models to get better understanding of db architecture
- used grep to find out where stats where coming from in ui (which was mostly pointless)
- on realising that they are cached by refresh_stats used pdb to step through until i found what looked like a good place to add a filter
- checked that stats are correctly updated when further translations are completed

### CODE REVIEW

**Comment by jleclanche** [comment]
I don't think filtering on just endswith "pot" is the appropriate way to exclude template files. @julen @unho do we have a way of checking whether a file is a template?

**Comment by phlax** [comment]
yep that was a concern, but .po files and .pot files share the same file_class, so i figured it was the only way

**Comment by phlax** [comment]
...and afaict there is no content/mimetype stored on the filefield, or file classes

**Comment by julen** [comment]
A couple ways I can see ([1](https://github.com/translate/pootle/blob/d6c4809fe881dac706908c22d304a24c24c93052/pootle/apps/pootle_project/models.py#L429-L437), [2](https://github.com/translate/pootle/blob/d6c4809fe881dac706908c22d304a24c24c93052/pootle/apps/pootle_app/project_tree.py#L48-L64)) — not definitely filtering by a hard-coded *pot*.

**Comment by ta2-1** [comment]
Old `refresh_stats` command is going away (https://github.com/translate/pootle/issues/3693).
It's worth to fix https://github.com/translate/pootle/issues/3245 for `refresh_stats_rq` command.

**Comment by unho** [comment]
This was moved to #3934. Not sure about the reason.

**Comment by phlax** [comment]
i put it on a new branch/pr as i didn't know to force push my rebased repo

**Pull request closed without merging**
