### PR TITLE
Add CONTRIBUTING guide

### LINKED ISSUE #3999: Add a CONTRIBUTING page to Pootle Github project
We have the CONTRIBUTING page @jleclanche suggested and also examples such as [this](https://github.com/skidding/cosmos/blob/master/CONTRIBUTING.md)

This bug is to track the review and massage of those to build our own Pootle CONTRIBUTING page.

### PR DESCRIPTION
**Pull request by unho**
This replaces PR #4108.

Fixes #3999.

### CODE REVIEW

**Comment by julen** [comment]
I'd like to propose the following fixes: https://github.com/unho/pootle/compare/docs/contributing...julen:pr/4228-fixes

Ideally I'd prefer this to be markdown rather than rST too, not sure what your impressions are on the matter.

**Comment by phlax** [comment]
i tend to avoid markdown these days as ive hit compatibility issue -  eg on pypi with it

**Comment by unho** [comment]
I am ok with your suggestions except https://github.com/unho/pootle/commit/f63a5b26507ab6592e22c61c6fd940153d51f14f since IMHO if we tell people to ask for the better way to contribute we should point them to the Pootle development IRC channel (#pootle-dev) instead to the support one (#pootle). Anyway I will pick the "seek for help" rewording from that commit, and the rest of the changes.

Regarding using Markdown, we are using reStructuredText for the README, so I think it is better to stick with it.

**Comment by phlax** [comment]
we have to use rst for the README or it wont render on pypi

**Comment by julen** [comment]
I won't bike-shed, however note this doc is to be consumed by GH, not PyPI.

OTOH, the motivation behind the IRC change is the following: currently, many of the issues being opened are actual support questions. Another way to avoid that is to point people to a support channel, which #pootle-dev is not.

**Comment by unho** [comment]
Ok, will use #pootle.

**Comment by unho** [comment]
Included all @julen suggestions.

**Comment by unho** [comment]
@translate/core Any gtm?

**Comment by phlax** [comment]
gtm

**Comment by unho** [comment]
Ok, I am merging this one too.

**Pull request merged**
