### PR TITLE
Fix missing _get_total_wordcount on Store

### PR DESCRIPTION
**Pull request by gterzian**
WIP for https://github.com/translate/pootle/issues/3819

### CODE REVIEW

**Comment by unho** [comment]
Hi.
I think the right fix is to instead alter https://github.com/translate/pootle/blob/master/pootle/apps/pootle_terminology/views.py#L110 to be:

```python
        source_words = sum(store. _get_wordcount_stats()['total']
```

since the `_get_total_wordcount` method was dropped as part of 2c31ad9c.

**Comment by gterzian** [comment]
@unho Thanks for the suggestion! I think it's a good idea, and I couldn't quickly find an existing test for that view or a similar one which I could use as an example to write such a test myself. Could you perhaps point me in the right direction?

**Comment by unho** [comment]
I myself am a bit lost when it comes to testing. Perhaps @julen can provide some hints.

**Comment by gterzian** [comment]
@unho, OK I understand. @julen, please advise on this. One of the reason I just re-added the method was so I wouldn't have to write a test for the whole view, especially since there are already model unit-tests I could quickly use as a template.

**Comment by dwaynebailey** [comment]
@gterzian this doesn't really address the issue as raised in #3819, this is a bandaid.  At the end of the report you can see the real proposed solution which is to remove auto generation of terminology from Pootle.

I'd suggest doing that or picking another problem to address.  I like that you've added tests and such but this doesn't make much sense to land if a) we'll rip it out later and b) it clutters the code we're trying to cleanup with methods that we'll want to remove anyway.

**Comment by gterzian** [comment]
@dwaynebailey  Thanks Dwayne. You obviously have a great team and done an equally great job at steering this project over the years, I take your feedback very seriously.

I'm sure you're aware I'm doing this as part of your interview process, and at this point we might do best to focus on figuring out whether we're going to be a good fit at all. I might have totally different ideas than you when it comes to writing software, and I'de be very interested in hearing about those differences. So I'm going to go ahead and tell you a bit more about how I like to work, in the context of the current discussion: 

* Bandaid is a honking great idea, and we need more of that :smiley:  
* Pootle is a huge project, and although it was obviously written by Python experts, the inevitable complexity has crept up over the years. That one module alone is 2000 lines. I think it could be great to have hundreds of pieces of "bandaid" (meaning small changes, with tests) applied steadily to the project. 
* Perhaps in this particular case, it would be better to remove this terminology app altogether. Still, there's always a quick and small fix you can apply today, and a larger more difficult task you can do, well, let's say "some other day". 
* One of my favorite past-times is to focus on making it easy for people to write tests. Have you considered switching to using `unittest`, perhaps combined with a tool like https://github.com/Fluxx/exam ? 

So that's it. I guess I'm just a simple "bandaid" type of guy. I'd be very interested in hearing your and your team's thoughts on the above points. It could be really helpful to find out if we're a good fit :smile:

**Comment by julen** [comment]
@gterzian thanks for your effort on trying to fix the feature. However, as @dwaynebailey says the intention of #3819 is to get rid of the feature no more.

Seeing that this was resulting in unrelated discussions and with the will to keep us focused and avoid non-productive efforts, I've already wiped out the feature.

Feel free to continue out of this PR with any other discussions you might wanna bring up.

**Pull request closed without merging**
