### PR TITLE
Enable PEP257 testing and fix hanging fruit

### LINKED ISSUE #4212: Automate pep257 - docstring - checks
PEP257 defines docstring conventions and we can test for them using the [pep257 tool](http://pep257.readthedocs.org/en/latest/error_codes.html)

### PR DESCRIPTION
**Pull request by dwaynebailey**
Fixes #4212 but should land post 2.7.3

* Enables PEP257 checking in Travis (cost 7s).  
* Makes current clean checks hard requirements
* Fixes some of the low hanging fruit

Big remaining issues are:
* Missing docstrings
* Single single first line (jury out on if we actually want this
* D4 checks which relate to word choice Return over Returns, Test over Tests.

### CODE REVIEW

**Comment by julen** [comment]
I didn't check the actual contents yet, nevertheless in terms of the Travis cost, I think we'd be better off placing this as a separate task, so that it's not run 3 times but just once. Basically the same applies to any other non DB-dependant checks.

**Comment by dwaynebailey** [comment]
@julen lets deal with separation of meta from real tests in another issue.  7s is a small cost and I'd rather not confuse issues.

**Comment by julen** [comment]
Agreed — since you stressed the penalty thought you'd be worried about it right now.

**Comment by dwaynebailey** [comment]
@julen nah the other way around, wanted to stress that it wasn't costing minutes

**Comment by unho** [comment]
lgtm

**Comment by phlax** [comment]
lgtm

**Pull request merged**
