### PR TITLE
Move core to Allauth

### PR DESCRIPTION
**Pull request by jleclanche**
Bit of a WIP but open for reviews.

### CODE REVIEW

**Comment by jleclanche** [comment]
cc @julen @unho @dwaynebailey

**Comment by jleclanche** [comment]
@iafan This is actually ready for UI review. There shouldn't be any actually changes in the templates from core currently, just a bit of shuffling around with the template names.

**Comment by jleclanche** [comment]
merged to `allauth` branch

**Comment by dwaynebailey** [comment]
This is a testing review.  I setup Pootle on mysql with MyISAM, using syncdb, migrate, initdb to get the server setup.

I noted these issues in testing:

- "Table 'pootle.account_emailaddress' doesn't exist".  This occurs when trying to signin and also when trying submitting the lost password form.
- b1e045f86bf0ac31c865e07a2a9958acdf8d68b4 LOGIN_REDIRECT_URL = "/" - currently we redirect to the place from which the user requested a login.  Is reverting to / something planned temporary or in error?
- CAN_REGISTER = True, but I can't find any access to a registration form from the main login Window
- The pages don't expose the required functionality outlines in issue #3343. Referring to the mockups:
  - The login page (3) doesn't expose all the needed functionality
  - Not sure how to enable social authentication to validate operation of (1)
  - Didn't test (4), login when singups are disabled, as without signins having needed (3) functionality I assumed it isn't implemented
  - Can't test singups so can't test what is exposed for (5) (form for signing up as a new user)
  - Reset password (6) doesn't expose all the needed items.  It also hits the Table issue mentioned above so can't test any of the results of a reset request.
  - Couldn't test activation of an account (8), or password reset (9) without being able to login or create new accounts.

**Comment by jleclanche** [comment]
> "Table 'pootle.account_emailaddress' doesn't exist". This occurs when trying to signin and also when trying submitting the lost password form.

I had that and migrate took care of the issue. Hmm...

**Comment by jleclanche** [comment]
> b1e045f LOGIN_REDIRECT_URL = "/" - currently we redirect to the place from which the user requested a login. Is reverting to / something planned temporary or in error?

This is the default redirect url. It redirects to ?next if it exists.

**Comment by jleclanche** [comment]
I kept social auth disabled because it's disabled in master and we don't have a good UI for it. It's easy enough to enable when we get to that.

Closed signups are implemented in allauth with the help of 6981a540ee580b44110f19ca71595abc3a9930d0 and only require a setting.

**Comment by unho** [comment]
Just did a very quick check and I found that it would be easier if we can keep a 2 spaces indent for HTML as told in the styleguide since that would imply less diff to review.

**Comment by dwaynebailey** [comment]
> I kept social auth disabled because it's disabled in master and we don't have a good UI for it. It's easy enough to enable when we get to that.

OK, but that's needed for any styling executed by EN so I'd assume since its in the basic mockups that we'd have it on by default.

> Closed signups are implemented in allauth with the help of 6981a54 and only require a setting.

Which setting? There are no signups at the moment with ``CAN_REGISTER = True``.  Either that needs to go and use the allauth setting, or the signups needs proper exposure as per mockups.

**Comment by dwaynebailey** [comment]
Another batch of review feedback.  *The missing Table issue was bustage in ``django-allauth==0.19.0``*

Workflow issues (@jleclanche mostly)
- Settings->Reset Password - goes to reset password dialogue which asks for an email address to initiate password reset.  Current core goes to the actual reset password dialogue.  I think the former is more desirable here.
- Register screen - @jleclanche says is at /accounts/allauth/register/ - gives a 404.
- Signin and Signout produce notices - not present in https://core-translate.stage.evernote.com/

Styling related issues (@iafan and @jleclanche):
- Signin and Signout all post redundant message boxes, that need to be dismissed, to declare that the action has been successful.  Lets rather report errors and assume success doesn't need any reporting.
- Others reported on #3343

What does work:
- Login works
- Logout works
- Reset password via emails send correct link
- Password reset works after getting the reset link

**Comment by jleclanche** [comment]
> Signin and Signout produce notices - not present in https://core-translate.stage.evernote.com/

Noticed that. I'm not sure how to get rid of them - it's possibly something we'll have to ignore in js. Im gonna leave it in for now because it could simply be integrated as part of the signin workflow instead of removed.

**Comment by jleclanche** [comment]
@julen @iafan This can either be merged imminently, or it can wait for further styling while it's still in upstream/allauth. What's your take on it?

**Comment by jleclanche** [comment]
@iafan Re signin/signout messages: We want you guys to take a decision about what we do with these notices, since they could present themselves useful for the UI. If they are to be removed, I am guessing they just have to be ignored in javascript and not displayed.

**Comment by dwaynebailey** [comment]
@iafan Just so that things are doubly clear:

1. This is now ready for you to take over and style and its ready for Evernote to look at the Evernote backend
2. The implementation has been done such that it could land now on core, only issue is the login logout message that @jleclanche mentioned which are I think a regression.  Thus this can land now on core.  Doing that would assist us in that it would make migrations easier, not sure though how it could/would live alongside current EN login system

**Comment by iafan** [comment]
@jleclanche, let's keep the development in the branch and merge this into core once this is fully implemented and ready for production (keep in mind that we do frequent releases off the core, so it should be in a stable state at any time).

**Comment by iafan** [comment]
@ta2-1, can you please have a look at this rather sooner than later and see how we can re-integrate Evernote flow according to our UI specs and whether we will need any changes/tweaks/help from @jleclanche to make this happen?

**Comment by julen** [comment]
Some notes from a quick overview:
* In some template *Sign In* has been renamed to *Log In*. We have been using the former, so this is a reminder for ourselves to keep that consistent.
* Re. messages: they come from the messages framework and [according to the docs](http://django-allauth.readthedocs.org/en/latest/advanced.html#messages) they can be ignored by overriding its templates. The truth is the [messages framework](https://docs.djangoproject.com/en/1.6/ref/contrib/messages/) is only used in a [single place](https://github.com/translate/pootle/blob/b1329ce44c8bfb7f4b74aa23e37dd7a41ad55411/pootle/apps/evernote_auth/views.py#L61) currently, and since we'll be integrating EN auth as an allauth provider, this might be a good time to revisit if we actually need it.
* In `/accounts/allauth/*` URLs *allauth* is superfluous, can we get rid of that in favor of `/accounts/`?
* Moving `pootle_profile` URLs to `/profiles/` breaks our URLs. We want to keep having public user-related pages available at `/user/<username>/`.
* As @unho said, please keep 2 space indents in HTML.

**Comment by jleclanche** [comment]
Thanks, will fix all that today. Use Sign In everywhere then?

**Comment by dwaynebailey** [comment]
> Thanks, will fix all that today. Use Sign In everywhere then?

The mockups use Sign in everywhere, so lets follow the mockups if any changes where made.

**Comment by iafan** [comment]
> Settings->Reset Password - goes to reset password dialogue which asks for an email address to initiate password reset. Current core goes to the actual reset password dialogue. I think the former is more desirable here.

I'm kind of inclined to keep it the way Jerome did, since this simplifies the code and doesn't introduce any new UI. People seldom change their passwords unless forced to, so it's not the feature I'd invest much time into.

**Pull request closed without merging**
