### PR TITLE
Resize virtual path field

### PR DESCRIPTION
**Pull request by prasastoadi**
Increase the size of virtual path input field as stated here https://github.com/translate/pootle/issues/4180

### CODE REVIEW

**Comment by phlax** [comment]
hi @prasastoadi as there is already an open bug for this im gonna close as a duplicate

**Comment by jayvdb** [comment]
@prasastoadi "codecov" will be much happier if you can add a unit test for `PageCreateView.get_form`

**Comment by unho** [comment]
Note the placeholder text is translatable, so the length increase can be considerably larger.

**Comment by unho** [comment]
This form field is for  [this model field ](https://github.com/translate/pootle/blob/master/pootle/apps/staticpages/models.py#L37) which is 100 characters long. My guess is that setting 100 chars would be enough.

**Comment by unho** [comment]
Landed in https://github.com/translate/pootle/commit/262981d87d8c404a115ef6a0b0d2c2d7a324d9dc. Thanks for your contribution!

**Pull request closed without merging**
