### PR TITLE
Remove BaseRunCommand

### PR DESCRIPTION
**Pull request by dwaynebailey**
This is the first of the PRs to move from optparse to argparse.

### CODE REVIEW

**Comment by julen** [comment]
The changes look good.

**Comment by julen** [comment]
As an aside comment, and looking at what's being remove here, I wonder if since the removal of CherryPy (and hence any use of `BaseRunCommand`) anyone has checked static files are properly served in test installations: FWIW the `app = StaticFilesHandler(WSGIHandler())` line ensured this.

**Comment by dwaynebailey** [comment]
@unho or @ta2-1 in your reviews could you check https://github.com/translate/pootle/pull/4403#issuecomment-173145026

**Comment by unho** [comment]
lgtm.

**Comment by ta2-1** [comment]
@julen, I checked that static files are properly served on my local machine with `debug=True`. I'm not sure if this is what you were worried about.

**Comment by julen** [comment]
My worry was basically when someone installs Pootle via pip following the docs, static assets might not work. So this should work without altering the basic settings provided by `pootle init` (this includes for instance `DEBUG = False`).

**Comment by unho** [comment]
I tried running `master` locally using `DEBUG = False` and it is serving the static assets.

**Comment by julen** [comment]
In case there was some misunderstanding, and just to make it clear, this is not about the value of `DEBUG` specifically, but rather about installing the package and being able to run Pootle smoothly when one follows the installation instructions. If you already checked that, then that's it!

**Comment by julen** [comment]
Also, from my understanding of `runserver`, this would need the [`--insecure flag`](https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#django-admin-option---insecure) in order for static files to work in a test installation.

**Comment by unho** [comment]
@julen Checked again, redoing everything from scratch, using a completely fresh checkout and using `DEBUG = False` and `--insecure` and it fails because of the assets. It is not even necessary to run with `--insecure` to get the error.

```pytb
[2016-01-20T16:16:22]	Internal Server Error: /projects/
Traceback (most recent call last):
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django_assets/templatetags/assets.py", line 87, in render
    for url in bundle.urls():
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 747, in _urls
    return [self._make_output_url(ctx)]
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 704, in _make_output_url
    version = self.get_version(ctx, refresh=ctx.auto_build)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 315, in get_version
    'determined dynamically, because: %s') % (self, reason))
BundleError: Cannot find version of <Bundle output=css/common.min.%(version)s.css, filters=[<webassets.filter.cssmin.CSSMin object at 0x7fc2c3d6be10>], contents=('css/style.css', 'css/actions.css', 'css/breadcrumbs.css', 'css/buttons.css', 'css/contact.css', 'css/error.css', 'css/auth.css', 'css/magnific-popup.css', 'css/navbar.css', 'css/odometer.css', 'css/popup.css', 'css/react-select.css', 'css/tipsy.css', 'css/sprite.css', 'css/select2.css', 'css/select2-pootle.css', 'css/scores.css', 'css/user.css', 'css/welcome.css')>. There is no manifest which knows the version, and it cannot be determined dynamically, because: output target has a placeholder
2016-01-20 16:16:22,927 ERROR Internal Server Error: /projects/
Traceback (most recent call last):
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django_assets/templatetags/assets.py", line 87, in render
    for url in bundle.urls():
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 747, in _urls
    return [self._make_output_url(ctx)]
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 704, in _make_output_url
    version = self.get_version(ctx, refresh=ctx.auto_build)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 315, in get_version
    'determined dynamically, because: %s') % (self, reason))
BundleError: Cannot find version of <Bundle output=css/common.min.%(version)s.css, filters=[<webassets.filter.cssmin.CSSMin object at 0x7fc2c3d6be10>], contents=('css/style.css', 'css/actions.css', 'css/breadcrumbs.css', 'css/buttons.css', 'css/contact.css', 'css/error.css', 'css/auth.css', 'css/magnific-popup.css', 'css/navbar.css', 'css/odometer.css', 'css/popup.css', 'css/react-select.css', 'css/tipsy.css', 'css/sprite.css', 'css/select2.css', 'css/select2-pootle.css', 'css/scores.css', 'css/user.css', 'css/welcome.css')>. There is no manifest which knows the version, and it cannot be determined dynamically, because: output target has a placeholder
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 268, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/home/leo/probaptl/pootle/pootle/core/views.py", line 442, in server_error
    return django_500(request, template_name='errors/500.html')
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/views/defaults.py", line 45, in server_error
    return http.HttpResponseServerError(template.render())
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django_assets/templatetags/assets.py", line 87, in render
    for url in bundle.urls():
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 747, in _urls
    return [self._make_output_url(ctx)]
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 704, in _make_output_url
    version = self.get_version(ctx, refresh=ctx.auto_build)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 315, in get_version
    'determined dynamically, because: %s') % (self, reason))
BundleError: Cannot find version of <Bundle output=css/common.min.%(version)s.css, filters=[<webassets.filter.cssmin.CSSMin object at 0x7fc2c3d6be10>], contents=('css/style.css', 'css/actions.css', 'css/breadcrumbs.css', 'css/buttons.css', 'css/contact.css', 'css/error.css', 'css/auth.css', 'css/magnific-popup.css', 'css/navbar.css', 'css/odometer.css', 'css/popup.css', 'css/react-select.css', 'css/tipsy.css', 'css/sprite.css', 'css/select2.css', 'css/select2-pootle.css', 'css/scores.css', 'css/user.css', 'css/welcome.css')>. There is no manifest which knows the version, and it cannot be determined dynamically, because: output target has a placeholder
[20/Jan/2016 16:16:22] "GET /projects/ HTTP/1.1" 500 59
[20/Jan/2016 16:16:22] "GET /favicon.ico HTTP/1.1" 301 0
[2016-01-20T16:16:22]	Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response
    response = callback(request, **param_dict)
  File "/home/leo/probaptl/pootle/pootle/core/views.py", line 438, in page_not_found
    return django_404(request, template_name='errors/404.html')
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/views/defaults.py", line 22, in page_not_found
    body = template.render(context, request)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django_assets/templatetags/assets.py", line 87, in render
    for url in bundle.urls():
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 747, in _urls
    return [self._make_output_url(ctx)]
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 704, in _make_output_url
    version = self.get_version(ctx, refresh=ctx.auto_build)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 315, in get_version
    'determined dynamically, because: %s') % (self, reason))
BundleError: Cannot find version of <Bundle output=css/common.min.%(version)s.css, filters=[<webassets.filter.cssmin.CSSMin object at 0x7fc2c3d6be10>], contents=('css/style.css', 'css/actions.css', 'css/breadcrumbs.css', 'css/buttons.css', 'css/contact.css', 'css/error.css', 'css/auth.css', 'css/magnific-popup.css', 'css/navbar.css', 'css/odometer.css', 'css/popup.css', 'css/react-select.css', 'css/tipsy.css', 'css/sprite.css', 'css/select2.css', 'css/select2-pootle.css', 'css/scores.css', 'css/user.css', 'css/welcome.css')>. There is no manifest which knows the version, and it cannot be determined dynamically, because: output target has a placeholder
2016-01-20 16:16:22,997 ERROR Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response
    response = callback(request, **param_dict)
  File "/home/leo/probaptl/pootle/pootle/core/views.py", line 438, in page_not_found
    return django_404(request, template_name='errors/404.html')
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/views/defaults.py", line 22, in page_not_found
    body = template.render(context, request)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django_assets/templatetags/assets.py", line 87, in render
    for url in bundle.urls():
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 747, in _urls
    return [self._make_output_url(ctx)]
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 704, in _make_output_url
    version = self.get_version(ctx, refresh=ctx.auto_build)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 315, in get_version
    'determined dynamically, because: %s') % (self, reason))
BundleError: Cannot find version of <Bundle output=css/common.min.%(version)s.css, filters=[<webassets.filter.cssmin.CSSMin object at 0x7fc2c3d6be10>], contents=('css/style.css', 'css/actions.css', 'css/breadcrumbs.css', 'css/buttons.css', 'css/contact.css', 'css/error.css', 'css/auth.css', 'css/magnific-popup.css', 'css/navbar.css', 'css/odometer.css', 'css/popup.css', 'css/react-select.css', 'css/tipsy.css', 'css/sprite.css', 'css/select2.css', 'css/select2-pootle.css', 'css/scores.css', 'css/user.css', 'css/welcome.css')>. There is no manifest which knows the version, and it cannot be determined dynamically, because: output target has a placeholder
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 175, in get_response
    response = self.get_exception_response(request, resolver, 404)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_exception_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 268, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/home/leo/probaptl/pootle/pootle/core/views.py", line 442, in server_error
    return django_500(request, template_name='errors/500.html')
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/views/defaults.py", line 45, in server_error
    return http.HttpResponseServerError(template.render())
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/django_assets/templatetags/assets.py", line 87, in render
    for url in bundle.urls():
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 747, in _urls
    return [self._make_output_url(ctx)]
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 704, in _make_output_url
    version = self.get_version(ctx, refresh=ctx.auto_build)
  File "/home/leo/.virtualenvs/whatever/local/lib/python2.7/site-packages/webassets/bundle.py", line 315, in get_version
    'determined dynamically, because: %s') % (self, reason))
BundleError: Cannot find version of <Bundle output=css/common.min.%(version)s.css, filters=[<webassets.filter.cssmin.CSSMin object at 0x7fc2c3d6be10>], contents=('css/style.css', 'css/actions.css', 'css/breadcrumbs.css', 'css/buttons.css', 'css/contact.css', 'css/error.css', 'css/auth.css', 'css/magnific-popup.css', 'css/navbar.css', 'css/odometer.css', 'css/popup.css', 'css/react-select.css', 'css/tipsy.css', 'css/sprite.css', 'css/select2.css', 'css/select2-pootle.css', 'css/scores.css', 'css/user.css', 'css/welcome.css')>. There is no manifest which knows the version, and it cannot be determined dynamically, because: output target has a placeholder
[20/Jan/2016 16:16:22] "GET /favicon.ico/ HTTP/1.1" 500 59
```

**Comment by ta2-1** [comment]
@unho did you checked this on this PR or current master? I had a similar bundle error on current master.

**Comment by unho** [comment]
@ta2-1 I used current master since this PR is not introducing the issue.

**Pull request closed without merging**
