### PR TITLE
Move core to Allauth

### PR DESCRIPTION
**Pull request by jleclanche**
Moved from #3447

### CODE REVIEW

**Comment by julen** [comment]
This still breaks user profile URLs as [mentioned in a previous comment](https://github.com/translate/pootle/pull/3447#issuecomment-69550987). @jleclanche can you move them back to `/user/<username>/` please?

**Comment by dwaynebailey** [comment]
@jleclanche I got this traceback related to gravatars:

```pytb
Traceback (most recent call last):
  File "/Users/dwayne/dev/pootle-verbatim-test/pootle/apps/pootle_app/management/commands/__init__.py", line 66, in do_translation_project
    self.handle_all_stores(tp, **options)
  File "/Users/dwayne/dev/pootle-verbatim-test/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 96, in handle_all_stores
    **options)
  File "/Users/dwayne/dev/pootle-verbatim-test/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 219, in process
    self._set_last_action_stats(store_fk_filter)
  File "/Users/dwayne/dev/pootle-verbatim-test/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 381, in _set_last_action_stats
    'snippet': sub.get_submission_message()
  File "/Users/dwayne/dev/pootle-verbatim-test/pootle/apps/pootle_statistics/models.py", line 210, in get_submission_message
    "gravatar_url": displayuser.gravatar_url(20),
AttributeError: 'User' object has no attribute 'gravatar_url'
```

**Comment by julen** [comment]
As mentioned on IRC few days ago, can we please take away those commits that are out of the scope described in #3343? The feature is big enough and adding extra sources of bugs to it is completely unnecessary so let's avoid it please.

**Comment by julen** [comment]
Closing for now — this will be superseded by a new PR for the whole thing with greater detail.

**Pull request closed without merging**
