### PR TITLE
Upgrade requirements

### PR DESCRIPTION
**Pull request by unho**

### CODE REVIEW

**Comment by julen** [comment]
Looks good to me, not sure about the PG failure on Travis though.

**Comment by phlax** [comment]
> not sure about the PG failure on Travis though.

this has happened a couple of times before seemingly randomly, but i thought it had gone away.

i think there is a problem with ordering not being enforced on units in the export view.

**Comment by unho** [comment]
Updated the PR to include a maximum version for RQ.

Re Travis failure that is some error I already have seen in other PRs that comes and goes.

**Comment by ta2-1** [comment]
I reckon that `rq==0.5.5` doesn't affect us. lgtm.

**Comment by ta2-1** [comment]
@unho with #4360 there is no need to change rq version here.

**Comment by unho** [comment]
@ta2-1 Great! Will drop RQ version change then. And will merge the PR.

**Pull request merged**
