### PR TITLE
Docs: Minor cleanups on upgrading and 2.6 release notes

### PR DESCRIPTION
**Pull request by unho**

### CODE REVIEW

**Comment by unho** [comment]
@jleclanche @dwaynebailey Please review.

**Comment by unho** [comment]
@jleclanche @dwaynebailey Now the upgrading docs are live, and also has been added the step to upgrade first to Pootle 2.6.0 if necessary. Please review again and gtm if possible so this can be landed asap before becoming my nightmare of the month.

**Comment by unho** [comment]
@jleclanche @dwaynebailey Is there any issue? If not, please gtm.

**Comment by dwaynebailey** [comment]
@unho gtm

**Pull request merged**
