### PR TITLE
Upgrade remnants for 2.6 branch

### PR DESCRIPTION
**Pull request by unho**

### CODE REVIEW

**Comment by unho** [comment]
@jleclanche @dwaynebailey Please review and test if possible.

**Comment by unho** [comment]
@dwaynebailey @jleclanche This PR is ready for final review as well.

**Comment by unho** [comment]
@dwaynebailey Dropped the commit that removed the South migration history and postponed issue #3597.

**Comment by unho** [comment]
@jleclanche @dwaynebailey Is there any issue? If not, please gtm.

**Comment by dwaynebailey** [comment]
@unho lgtm but I must admit I really don't understand the two migrations.  I'm assuming the 'submissions without submitters' relate to the issues I reported previously and for which you asked for counts on mlo and LO.  Revision model, I'm in the dark.

**Comment by unho** [comment]
@dwaynebailey Previously master had a Revision model that persisted the last revision number on the DB, but now it is using Redis for that. So since master dropped the DB model, there is no reason to keep it on stable/2.6.0 since it was only backported to provide a working upgrade.

About 'submissions without submitters'. In some legacy installs (mlo and libo for example) there might exist those. But a submission without submitter is useless for us, and even more, can throw tracebacks. So since we can't recover the lost submitter in most cases, it is preferable to just drop them, so we don't get tracebacks in the future.

**Pull request merged**
