### PR TITLE
README: removed redundant badges

### PR DESCRIPTION
**Pull request by julen**
Travis status is well enough.

### CODE REVIEW

**Comment by unho** [comment]
@julen Despite them being redundant, I think they provide useful information in one sight.

**Comment by julen** [comment]
So perhaps you can add them somewhere else, but bloating the README with them is redundant as you say.

**Comment by jleclanche** [comment]
I'm +1 on this, badge bloat looks as professional as blinking "New" gifs on a website.

**Comment by unho** [comment]
@julen The idea behind the badges was to see them as soon as you visit the project main page, which prominently displays a rendered version of the README, so if those are going to be removed from there, they are definitely not being put in another place.

Since you both want this to be gone, then merge the PR.

**Pull request merged**
