### PR TITLE
Handle multiple config locations

### LINKED ISSUE #6573: [RFC] Move pootle.conf to venv/app root
As suggested by @luistce it might make more sense for POOTLE_SETTINGS to point to pootle.conf in the venv or app root.

It would be more obvious/explicit, but would also allow same user to be running multiple instances

### PR DESCRIPTION
**Pull request by phlax**
this PR will take settings from:

- /etc/pootle/pootle.conf
- ~/pootle/pootle.conf
- $VIRTUAL_ENV/pootle.conf

in that order

fixes #6573 

this PR does not touch docs, as that will be handled as part of #5210

### CODE REVIEW

**Comment by dwaynebailey** [comment]
@phlax after cleaning out any existing `90-local.conf`, `~/.pootle/pootle.conf` and `VENV/pootle.conf`  I get the following message when running any command:

```
(pootle)~/dev/pootle $ pootle --help
2017-07-24 10:58:33,045 WARNING 'POOTLE_SETTINGS' environment variable has not been set.

Traceback (most recent call last):
  File "/Users/dwayne/dev/envs/pootle/bin/pootle", line 11, in <module>
    load_entry_point('Pootle', 'console_scripts', 'pootle')()
  File "/Users/dwayne/dev/pootle/pootle/runner.py", line 355, in main
    django_settings_module='pootle.settings')
  File "/Users/dwayne/dev/pootle/pootle/runner.py", line 304, in run_app
    caches = settings.CACHES.keys()
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/conf/__init__.py", line 116, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

Then if I run `pootle init` and it creates the `VENV/pootle.conf` file,  still get this error.

**Comment by dwaynebailey** [comment]
@phlax seems `default=""` causes problems.  Also if I have only `~/.pootle/pootle.conf` even with `default=default_settings_path` I get that same TB.

**Comment by dwaynebailey** [comment]
@phlax works perfectly in VENV/pootle.conf, however if I `mv VENV/pootle.conf ~/.pootle/` then I get the following TB

```pytb
(pootle)~/dev/pootle $ mv /Users/dwayne/dev/envs/pootle/pootle.conf ~/.pootle/
(pootle)~/dev/pootle $ pootle runserver --insecure
Traceback (most recent call last):
  File "/Users/dwayne/dev/envs/pootle/bin/pootle", line 11, in <module>
    load_entry_point('Pootle', 'console_scripts', 'pootle')()
  File "/Users/dwayne/dev/pootle/pootle/runner.py", line 356, in main
    django_settings_module='pootle.settings')
  File "/Users/dwayne/dev/pootle/pootle/runner.py", line 306, in run_app
    caches = settings.CACHES.keys()
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/conf/__init__.py", line 116, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

**Comment by dwaynebailey** [comment]
If there is no config file we also get above traceback.  Do we want to catch missing pootle.conf and force `pootle init`? I know we reverted that before but this lack of info could be confusing to someone who just hasn't run `pootle init`

**Comment by unho** [comment]
lgtm after Travis passes.

**Pull request merged**
