### PR TITLE
Language list: use simplified names

### LINKED ISSUE #3700: Overview dropdown is using ISO639 names and not simplified toolkit names
E.g. nso is using "Pedi; Sepedi; Nothern Sotho" instead of simply 'Northern Sotho'

### PR DESCRIPTION
**Pull request by julen**
At the same time this enables localized language names where applicable.

Please test with different UI locales — I couldn't do it since iso-codes seems broken on my end.

Fixes #3700.

### CODE REVIEW

**Comment by unho** [comment]
@julen lgtm. Couldn't test because iso-codes is also not working on my local environment.

**Comment by julen** [comment]
@dwaynebailey I'd be happy if you could test this on localized UIs.

**Comment by dwaynebailey** [comment]
@julen first part works, we're getting the properly simplified names.  Still checking localisation of language names.

**Comment by dwaynebailey** [comment]
@julen gtm nice fix

screen shot 2015-05-05 at 21 40 34

I installed the iso-codes package into my virtualenv and tested on German.

**Pull request merged**
