### PR TITLE
Changes in flush cache

### PR DESCRIPTION
**Pull request by unho**
@translate/core Should be easy and quick to review/reject.

Note: If this gets merged issue #3500 will need to be updated accordingly.

### CODE REVIEW

**Comment by jleclanche** [comment]
lgtm I guess

**Comment by julen** [comment]
-1 on `flush_` as I [mentioned a while ago](https://github.com/translate/pootle/issues/3500#issuecomment-73143799).

**Comment by unho** [comment]
@julen Would be `clear_stats` an acceptable compromise for now?

**Comment by jleclanche** [comment]
No, clear_stats has a completely different meaning.

**Comment by unho** [comment]
@julen @jleclanche So one of you says no `flush_` and the other says `clear_stats` has a different meaning. Can we please settle on one of them?

**Comment by julen** [comment]
I'd say go for `clear_`, — the underlying methods used by the command use the term *clear* too.

**Comment by unho** [comment]
I am merging this despite not everybody agrees with the naming. Renaming should be quite simple if we eventually agree on a new name.

**Pull request merged**
