### PR TITLE
Fix: allow admin users to view hidden project resources

### PR DESCRIPTION
**Pull request by phlax**

### CODE REVIEW

**Comment by unho** [comment]
To my understanding the hidden resources are the obsolete stores and directories. I don't think those should be displayed even to admins.

**Comment by phlax** [comment]
@unho - hmm - in that case we need to work out why they are being shown in the menu i reckon

**Comment by ta2-1** [comment]
@unho is right. we have only disabled (hidden) projects that should be shown to admin users.

**Comment by phlax** [comment]
PR withdrawn as better fix is to restrict what is shown in menu

**Pull request closed without merging**
