### PR TITLE
Update store syncer

### PR DESCRIPTION
**Pull request by phlax**
moves the sync_stores specific logic back to Store.sync so Syncer class can more easily be reused

### CODE REVIEW

**Comment by unho** [comment]
lgtm

**Comment by ta2-1** [comment]
lgtm besides triggered error with empty store with no units which doesn't have last_sync_revision value.

**Comment by phlax** [comment]
> empty store with no units which doesn't have last_sync_revision value.

this is fixed, and a test has been added

**Comment by unho** [comment]
Tested a bit and seems to work. gtm

**Pull request merged**
