### PR TITLE
Fix: dont set units with empty source to wc=1

### PR DESCRIPTION
**Pull request by phlax**
not entirely why this was setting unit wordcounts to 1 if source is empty, but it seems to break stuff and didnt seem to happen historically, so fix seems ok

fixes: #6507

### CODE REVIEW

**Comment by unho** [comment]
lgtm

**Comment by unho** [comment]
lgtm

**Comment by ta2-1** [comment]
I have 2 concerns here:
- state of a unit with empty source is ignored (though empty units should be marked as translated explicitly). if you need to set specific translation for units with empty source you won't be able to find them as untranslated.
https://mozilla.locamotion.org/eu/firefox_beta/translate/#filter=untranslated
- wordcount function can ignore a specific set of words such as `Pootle` which shouldn't be translated.

**Comment by phlax** [comment]
@ta2-1 not really following the issue you raise here

afaict the wordcount should just be what the wordcount function says - irrespective of state - similar with ignored words really

what do you suggest would be a better way to store wordcounts ?

**Comment by ta2-1** [comment]
@phlax 
There is inconsistence:
If you see zero incomplete wordcount you don't expect to see untranslated or fuzzy units.
And I'd say it's critical. 

I agree that setting wordcount to `1` is not perfect solution but it was made intentionally.

As perfect solution I can think about splitting incomplete unit count and incomplete word count and having two different numbers in stats.

Speaking about fixing mlo issue after cloning `ff_beta` I think empty unit states should be set to `translated` manually (though I'm not sure how it will affect `.po` files).

**Comment by phlax** [comment]
> As perfect solution I can think about splitting incomplete unit count and incomplete word count and having two different numbers in stats.

yep, i was just chatting with @dwaynebailey re this, and that was the conclusion i came to. Not sure how quickly we are gonna add that though

**Pull request merged**
