### PR TITLE
db: REXEXP is not present on PostgreSQL

### PR DESCRIPTION
**Pull request by dwaynebailey**
Please view.

PG uses !~ while the other DBs use NOT REGEXP. I'm not sure if there is a more elegant way of doing this.

### CODE REVIEW

**Comment by jleclanche** [comment]
This is an ok solution but I think there is a way to drop the regex entirely from the query. It's so nasty.

**Comment by unho** [comment]
Looks gtm.

**Comment by dwaynebailey** [comment]
@jleclanche can I get a GTM on this.  I also think there is something more elegant, but I don't think that is critical.  I can add FIXMEs to the code if needed, but I'd like to land this.

**Comment by jleclanche** [comment]
gtm but fix the typo please ;)

**Pull request merged**
