### PR TITLE
Pootle pytest

### PR DESCRIPTION
**Pull request by phlax**
Adding a pootle_pytest plugin containing any fixtures factories and utils for use in tests

### CODE REVIEW

**Comment by unho** [comment]
As far as I can tell there is nothing obviously wrong with this, and Travis seems to pass. lgtm

**Comment by unho** [comment]
Ran the tests locally and takes forever.

**Comment by phlax** [comment]
i reckon thats your machine 8/

running fine locally and on travis - https://travis-ci.org/translate/pootle/pull_requests

**Comment by julen** [comment]
@phlax can you explain what's the benefit of this? Currently I see only code being moved around, not sure if you plan for something else.

**Comment by phlax** [comment]
hi @julen - yep - pootle_fs in particular needs a pootle environment to run tests, and as a result i had to duplicate a lot of the test code. Putting fixtures/utils etc into a plugin allows me to re-use the Pootle test code in other packages.

**Comment by julen** [comment]
Cool fair enough.

**Pull request merged**
