### PR TITLE
Rename evernote_reports app to just reports

### PR DESCRIPTION
**Pull request by unho**
Tested and works both for fresh install and upgrade.

### CODE REVIEW

**Comment by jleclanche** [comment]
gtm

**Comment by julen** [comment]
I'd strongly prefer to be consistent with the entire codebase in respect to URL pattern naming and stick to the `pootle-reports-` prefix.

**Comment by unho** [comment]
@julen I don't disagree. Are you going to do it, or should I take the renaming?

**Comment by julen** [comment]
Feel free to go ahead and PR it.

**Pull request merged**
