### PR TITLE
Initdb: Add default project descriptions

### LINKED ISSUE #3416: Add default project descriptions
In order to get ``initdb`` running on ``core`` we had to drop the project [descriptions] since these move to staticpages on core.  This bug is to add those back.

To achieve that initdb should create static pages for these default projects that contain the content previously held in the [descriptions](https://github.com/translate/pootle/blob/96edf539/pootle/core/initdb.py#L300-L306).

### PR DESCRIPTION
**Pull request by unho**
Fixes #3416.

### CODE REVIEW

**Comment by dwaynebailey** [comment]
@unho yes drop those.  Pootle localisations should be centralised.

**Comment by unho** [comment]
@jleclanche @dwaynebailey Ready for final review.

**Comment by unho** [comment]
@jleclanche @dwaynebailey The concerns raised have been fixed. AFAICT these changes don't affect Evernote. So as soon as I get a gtm I will land this.

**Comment by unho** [comment]
@jleclanche @dwaynebailey Is there any issue? If not, please gtm.

**Comment by dwaynebailey** [comment]
@unho its gtm but I don't see a default description for the Terminology project.

**Comment by unho** [comment]
@dwaynebailey The default description is now being added as an announcement.

**Pull request merged**
