### PR TITLE
Allow admins to access disabled projects

### LINKED ISSUE #3451: Allow admins to access disabled projects
Currently admins cannot access disabled projects, it returns a 404 error. They should be able to access them, because they might be preparing a project (adjusting permissions etc.) prior to making it public.

For a enhanced user experience and to avoid admins shooting themselves in the foot, a message needs to be displayed when browsing disabled projects, indicating that while disabled, the project is only visible to admins. This is basically the same thing we do for inactive static pages.

### PR DESCRIPTION
**Pull request by julen**
This allows admins to access disabled projects, which currently 404s for everyone.

Fixes #3451.

### CODE REVIEW

**Comment by julen** [comment]
Would appreciate a review/test @iafan.

**Comment by iafan** [comment]
Testing on stage: the only minor thing I currently noticed is styling. The disclaimer box needs some margin between its top and the header. Can you adjust it to match the left/right margins between that box and the edges of the page?

**Comment by julen** [comment]
Thanks for reviewing, just fixed that and rebased on top of current master. Should be good to merge, then?

**Comment by iafan** [comment]
GTM

**Pull request merged**
