### PR TITLE
Add mailmap file

### PR DESCRIPTION
**Pull request by dwaynebailey**
Just cleans up the few user inconsistencies we have in git logs.

Would love signoff from those impacted: @iafan @friedelwolff @jleclanche @llimeht

### CODE REVIEW

**Comment by jleclanche** [comment]
:+1:

**Comment by llimeht** [comment]
Looks fine to me

**Comment by dwaynebailey** [comment]
OK, so I'm going to land this so I can close the PR. Even without all the signoffs. Friedel is just a name association and Igor can revert his changes if required.

**Comment by iafan** [comment]
I'm a bit late to  the party, but information about me looks correct.

+1

**Pull request merged**
