### PR TITLE
Irish translation back to 100%

### PR DESCRIPTION
**Pull request by kscanne**

### CODE REVIEW

**Comment by dwaynebailey** [comment]
Landed in 6ba06051c18f4580a3e8d07d42b87b39df41b0c9

@kscanne thanks once again

**Comment by unho** [comment]
@kscanne We have landed some changes in Pootle strings, so the translation will need another small update. Sorry for the inconveniences.

**Comment by kscanne** [comment]
No problem!  A quick question though... Since I've been submitting translations via PRs, I'm wondering about the status of the project here: http://pootle.locamotion.org/ga/pootle/     If a second contributor were to make changes to the translation through the Pootle server, would those be brought in to github automatically + periodically?  (I'm asking because we're trying to remove dependencies on me from our l10n processes!)

**Comment by unho** [comment]
Right now Pootle translations are synchronized manually and on a non-regular basis, but we have plans to put automatic regular synchronization in the future. Since you are submitting complete translations through PRs we are most likely going to apply your changes that the ones coming from that server. If you want to avoid such situation you can directly translate in http://pootle.locamotion.org/ga/pootle/ so your changes are blended with other people contributions.

**Comment by kscanne** [comment]
Thanks.  I'll continue with the PRs for now.

**Pull request closed without merging**
