### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by dwaynebailey**

### CODE REVIEW

**Comment by dwaynebailey** [comment]
rq 0.7.0 landed in c498ed695f5fad7e490911dfe89e75ebe20ecc9b

**Comment by unho** [comment]
@dwaynebailey All of this already landed, isn't it?

**Comment by dwaynebailey** [comment]
flake8 3.2.1 addressed in c2f04532

**Comment by dwaynebailey** [comment]
pytest-django 3.1.1 addressed in 519a0591

**Pull request closed without merging**
