### PR TITLE
Backports, fixes and missing migrations for 2.6

### PR DESCRIPTION
**Pull request by unho**

### CODE REVIEW

**Comment by unho** [comment]
Landed two of the commits (the ones that fixed #3726 and #3651). Held the rest until there is a PR for squashing the equivalent migrations on master branch.

Also it is necessary to check if there are duplicate `pootle_path` for `Directory` before running the migration, and abort with a warning so the user can check that. Duplicate dirs have been reported in the past.

All the migrations run ok both on a fresh 2.5.1 DB dump and in 2.6 DB.

**Comment by dwaynebailey** [comment]
Backporting evernote_reports doesn't make sense considering #3822 and for an app that only actually appears in 2.7.0, i.e. there is no real migration, I'm still at a complete loss as to why we need to backport that.  @jleclanche will have to explain this to me again.  But I've just done a migration to 2.7.0 and apart from where things are actually broken the migrations just seamlessly link between 2.6.0 and 2.7.0 so putting effort this seems like a spectacular waste of time.

**Comment by dwaynebailey** [comment]
I'd like to test these on a LO and mlo migrations.  But general review they look good.

On mlo I notice I have waffle tables.  We had that at one time, I'll check if there are any others that should be gone.

**Comment by unho** [comment]
Addressed the raised concerns.

**Comment by unho** [comment]
@dwaynebailey You said that you would test again but you didn't tell how it went. I tested again yesterday with no problem, so unless some problem is raised I will merge this today.

**Pull request merged**
