### PR TITLE
Shortcuts: switch to Mousetrap

### PR DESCRIPTION
**Pull request by julen**
The library is rock solid, allows to easily add cross-platform combos and it's
even available on npm.

Refs. #3136.

### CODE REVIEW

**Comment by julen** [comment]
Note this is a simple switch of the library, with no other changes intended. I'd appreciate if you could test nothing is broken.

**Comment by dwaynebailey** [comment]
Oops

**Comment by dwaynebailey** [comment]
@julen I managed to land this by pushing a doc fix, sorry.

My tests showed the following cf. http://docs.translatehouse.org/projects/pootle/en/latest/features/shortcuts.html

These work:
* Submit and move to next translation `Ctrl+Enter`	 
* Toggle the ‘Needs work’ flag	`Ctrl+Space`
* Toggle the suggest/submit mode `Ctrl+Shift+Space`

**Comment by iafan** [comment]
We had some problems across different platforms. Here's the relevant issue where we've been working on an updated set of shortcuts that would hopefully work more consistently: https://github.com/translate/pootle/issues/3136

**Comment by julen** [comment]
@dwaynebailey feel free to report any regressions separately. As @iafan says and your testing shows, previously not everything worked (at least on Mac).

**Comment by unho** [comment]
No, not everything worked. In fact the reason to have duplicate shortcuts was partly because of this.

**Pull request closed without merging**
