### PR TITLE
[RFC] Cleanup/quantifiedcode fixes

### PR DESCRIPTION
**Pull request by dwaynebailey**
Various cleanups picked up but https://www.quantifiedcode.com/

Some I'm not sure about, some are pretty straight forward and could land as is.  Would like some feedback as to which can land easily and which might be contentious.

### CODE REVIEW

**Comment by unho** [comment]
I like all the changes except "Avoid `None` as a redundant second argument to `dict.get()`". Can you please explain that one a bit more?

**Comment by dwaynebailey** [comment]
@unho I had similar reservations to ``dict.get('somthing', None)``.  By default ``get()`` will return ``None`` if the key is not found, thus ``None`` in this case is redundant and thus not needed.  I was in two minds as to whether we should all just know that or if it should be explicit.  Thus its here for comments.

Maybe more of a concern is that this does expose code like:

```py
a = dict.get('some', None)
if a:
    do_something()
```
When in fact this should be:

```py
a = dict.get('some', None)
if a in not None:
    do_something()
```

**Comment by unho** [comment]
I withdraw my previous block on "Avoid `None` as a redundant second argument to `dict.get()`" after reading https://docs.python.org/2/library/stdtypes.html#dict.get

So lgtm.

**Comment by unho** [comment]
Anyway I would include the explanation on the commit message, with the https://docs.python.org/2/library/stdtypes.html#dict.get link.

**Comment by julen** [comment]
I'm +1 on keeping `dict.get('foo', None)`, it's way more explicit than the default behavior. With this it's immediately clear subsequent checks need to be against `None`: `x is None`, `x is not None`.

The rest of the commits look perfect.

**Comment by dwaynebailey** [comment]
Landed this without the ``dict.get(,None)`` changes, decided to take @julen's take on this specifically because its explicit.

**Pull request merged**
