### PR TITLE
Adjust releasing for 2.7

### PR DESCRIPTION
**Pull request by unho**
@translate/core This gets back some missing stuff on the Makefile and provides and ugly hack to circumvent the absence of `SECRET_KEY` on build. I am not sure about these changes, so I am PRing.

### CODE REVIEW

**Comment by julen** [comment]
Doesn't setting `POOTLE_SETTINGS` to a settings file of your choice work? I'd prefer using what's already available over your hack.

**Comment by unho** [comment]
@julen Adjusted to meet your preferences. Any other concern?

**Comment by julen** [comment]
No concerns from my side provided your team is happy with it.

**Comment by jleclanche** [comment]
gtm

**Pull request merged**
