### PR TITLE
Cleanup: Drop handle_store() method from PootleCommand

### PR DESCRIPTION
**Pull request by unho**
@translate/core Please review

### CODE REVIEW

**Comment by julen** [comment]
Reasoning for this being?

While part of the code seems dead code, when in `update_stores` the `handle_translation_project()` method returns `True`, `handle_store()` is currently being called. This PR removes it for no apparent reason.

@ta2-1 could you double-check and confirm what I read is right?

**Comment by unho** [comment]
@julen You are right. I will adjust this to just drop `handle_store()` on the `flush_cache` and `sync_stores` management commands.

**Comment by ta2-1** [comment]
Few thoughts: 
I thought different command require different handlers and as I understood, there exist cases when it's enough to implement `handle_store()` only. It will allow to avoid some duplication of a code. Then `handle_store()` can leave in `__init__py`.
But we don't have such commands now and duplication of one for loop is not a big deal probably.

`update_stores` and `sync_stores` commands are addressed in #3583.

**Comment by unho** [comment]
I am going to directly merge the `handle_store()` method removal from `flush_cache`. As @ta2-1 already said #3583 handles the removal from `update_stores` and `sync_stores` so we can wait for it to be merged.

**Pull request closed without merging**
