### PR TITLE
Squash Django migrations on master

### PR DESCRIPTION
**Pull request by unho**
Counterpart of #3808

There are still `0002` migrations left:
-  `pootle_translationproject.0002` it is ok to be squashed if the data manipulation part is dropped, which already should have been run on the affected deployments.
- `accounts.0002` is more difficult to tell if it can be merged.

Part of #3311.

### CODE REVIEW

**Comment by jleclanche** [comment]
Why now?

**Comment by unho** [comment]
There is no reason to not squash the migrations now. If no new migrations are landed in master this just closes #3311.

**Comment by jleclanche** [comment]
If no new migrations are landed, which is a big if.

**Comment by unho** [comment]
If new migrations are landed we will squash those as well. No big deal.

**Comment by julen** [comment]
As @jleclanche says this is a big if, and we prefer to have to deal with this just once — realize existing deployments need manual work when updating master.

**Comment by unho** [comment]
I realize that. We can keep this open and update it as new migrations land on master, if they do.

**Comment by unho** [comment]
@translate/core Please review and test.

**Comment by ta2-1** [comment]
@unho, I've updated from the branch and run `migrate`. This is a result:
```
No changes detected
```

Seems squashed migrations are correct. 

But I wonder why we remove one migration files and leave others (see https://github.com/translate/pootle/blob/66e15d5d430c6d0c5042517f0b0cde7e9e717cfa/pootle/apps/pootle_app/migrations/0002_unique_pootle_path.py and https://github.com/translate/pootle/blob/7a93c430d7267dfad1b5111600a5150f67673592/pootle/apps/virtualfolder/migrations/0004_rename_is_browsable_to_is_public.py ). 

`migrate --list` returns
```
account
 [X] 0001_initial
 [X] 0002_email_max_length
accounts
 [X] 0001_initial
 [X] 0002_user_alt_src_langs
auth
 [X] 0001_initial
contenttypes
 [X] 0001_initial
evernote
 [X] 0001_rename_merged_users
 [X] 0002_move_to_allauth
evernote_auth
 [X] 0001_initial
 [X] 0002_evernoteaccount_user
pootle_app
 [X] 0001_initial
pootle_language
 [X] 0001_initial
pootle_project
 [X] 0001_initial
pootle_statistics
 [X] 0001_initial
pootle_store
 [X] 0001_initial
pootle_translationproject
 [X] 0001_initial
 [X] 0002_remove_translationproject_disabled
reports
 [ ] 0001_initial
 [ ] 0002_paidtask_user
 [X] 0003_rename_db_table
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
socialaccount
 [X] 0001_initial
staticpages
 [X] 0001_initial
virtualfolder
 [X] 0001_initial
 [ ] 0002_add_virtualfoldertreeitem
 [ ] 0003_drop_virtualfolder_ordering
 [X] 0004_rename_is_browsable_to_is_public
```
is this expectable?

**Comment by unho** [comment]
> But I wonder why we remove one migration files and leave others (see https://github.com/translate/pootle/blob/66e15d5d430c6d0c5042517f0b0cde7e9e717cfa/pootle/apps/pootle_app/migrations/0002_unique_pootle_path.py and https://github.com/translate/pootle/blob/7a93c430d7267dfad1b5111600a5150f67673592/pootle/apps/virtualfolder/migrations/0004_rename_is_browsable_to_is_public.py ). 

The ones that were removed (actually directly squashed into `0001_initial`) is because those are migrations that have been in `master` for a while. The ones that were squashed into a transitional squash migration is because those have been recently added, and some people might not have applied them yet. Thus we keep them. Those transitional migrations will be renamed to `0001_initial` in the future, thus dropping all other migrations they replace. Hopefully this will happen before 2.7 release.

> `migrate --list` returns
> ```
> account
>  [X] 0001_initial
>  [X] 0002_email_max_length
> accounts
>  [X] 0001_initial
>  [X] 0002_user_alt_src_langs
> auth
>  [X] 0001_initial
> contenttypes
>  [X] 0001_initial
> evernote
>  [X] 0001_rename_merged_users
>  [X] 0002_move_to_allauth
> evernote_auth
>  [X] 0001_initial
>  [X] 0002_evernoteaccount_user
> pootle_app
>  [X] 0001_initial
> pootle_language
>  [X] 0001_initial
> pootle_project
>  [X] 0001_initial
> pootle_statistics
>  [X] 0001_initial
> pootle_store
>  [X] 0001_initial
> pootle_translationproject
>  [X] 0001_initial
>  [X] 0002_remove_translationproject_disabled
> reports
>  [ ] 0001_initial
>  [ ] 0002_paidtask_user
>  [X] 0003_rename_db_table
> sessions
>  [X] 0001_initial
> sites
>  [X] 0001_initial
> socialaccount
>  [X] 0001_initial
> staticpages
>  [X] 0001_initial
> virtualfolder
>  [X] 0001_initial
>  [ ] 0002_add_virtualfoldertreeitem
>  [ ] 0003_drop_virtualfolder_ordering
>  [X] 0004_rename_is_browsable_to_is_public
> ```
> is this expectable?

No. It seems you haven't applied all the migrations in `reports` and `virtualfolder` apps. Once you apply those you should see the following for those two apps:

```
reports
 [X] 0001_squashed_0003_rename_db_table (3 squashed migrations)
virtualfolder
 [X] 0001_squashed_0004_rename_is_browsable_to_is_public (4 squashed migrations)
```

**Comment by julen** [comment]
My understanding is we wanted to start from a clean slate, i.e. all what's left is essentially *0001_initial*. /cc @jleclanche

**Comment by unho** [comment]
@julen Sure. But I didn't feel like immediately squashing everything to `0001_initial` was the right move just after merging that bunch of migrations.

**Comment by unho** [comment]
@julen Altered this PR to have a clean slate as requested.

@translate/core Please review and test.

**Comment by unho** [comment]
@translate/core Please review and test. Any gtm is welcome

**Comment by unho** [comment]
@dwaynebailey @jleclanche @julen @ta2-1 Please review and test. Any gtm is welcome as well.

**Comment by julen** [comment]
:+1: this looks and works good on our side.

**Comment by unho** [comment]
Will merge this tomorrow if nobody finds any issue.

**Pull request merged**
