### PR TITLE
Provide URLs for project/TP admin pages

### LINKED ISSUE #4524: Can’t navigate to browse/translate from admin pages
1. Go to a project
2. Go to TP admin using the dropdown.  Browse->Languages
3. Return to the Browse or Translate view.  Nothing happens
4. Move to the Permissions view, we move
5. Try move to Browse or Translate view again.  Nothing happens.

### PR DESCRIPTION
**Pull request by julen**
Fixes #4524.

### CODE REVIEW

**Comment by unho** [comment]
What about `pootle-projects-export`, `pootle-projects-translate`, `pootle-projects-browse`, `pootle-tp-export`, `pootle-project-export`, `pootle-language-export` removed in https://github.com/translate/pootle/commit/8fe18be59a1409ce21bce77c474cb6b61669f290.

**Comment by julen** [comment]
Export view is only accessible from the editor, which is not affected by the issue, and I don't see where the other `pootle-projects-*` patterns would apply either. Feel free to test and report if that's not the case though.

**Comment by unho** [comment]
@julen If while in a TP browse I go to "Terminology" and then try to go back it doesn't work.


> Export view is only accessible from the editor, which is not affected by the issue, and I don't see where the other `pootle-projects-*` patterns would apply either. Feel free to test and report if that's not the case though.

Tested and these are not necessary as you say.

**Comment by julen** [comment]
Good catch, that should now be fixed, it'd be cool if you could confirm.

**Comment by unho** [comment]
@julen It is fixed now. gtm.

**Pull request merged**
