### PR TITLE
Alternative method to handle raw font events

### PR DESCRIPTION
**Pull request by julen**
In this PR the [LF]-related issues reported in #5261 are taken care of by taking a different approach on how input events are handled. At the same time, this allows to avoid having to handle IMEs in application code (and workaround such as #5253).

The PR integrates the experiments @iafan did in an independent environment. Checklist:
* [x] Toggling the raw mode still has no effects
* [x] Values' state should totally be uncontrolled (to avoid conflicts, only rely on the DOM for this).
* [x] IE11 places the caret at the end after edits
* [x] Fix setting values from outside of the component tree
* [x] Make undo/redo remember cursor selections
* [x] Tests need to be adjusted
* [x] Dead code removal
* [x] Linting issue fixes
* [x] Cleanup the code for improved encapsulation of the functionality

**UPDATE**: This is now ready to check-in.

### CODE REVIEW

**Comment by dwaynebailey** [comment]
@julen tested with the `escapes.po` file as well as issues raised in #5261, I didn't see any issues related to those.

**Comment by dwaynebailey** [comment]
@julen lgtm based on my testing.  I'm not sure if anyone else wants to do a code review, I'll let them respond

**Comment by unho** [comment]
Just doing a quick code review.

**Comment by unho** [comment]
lgtm after quick code review and some testing on a staging server.

**Pull request merged**
