### PR TITLE
Allauth-based revamped auth workflow

### LINKED ISSUE #3343: Core: Reimplement allauth
Core uses the old Pootle authentication while 2.6 moved to allauth to provide a more modular approach to authentication.  The divergent authentication methods is a big blocker to merging the code.

The approach will be to land allauth on core as follow:

1. [x] Translate integrates allauth in core, using a feature branch for doing so (#3447 & #3468)
2. [x] Translate implements the workflow with Evernote's help (#3517)
3. [x] Evernote implements the allauth Evernote backend (#3515)
4. [ ] Evernote addresses styling UI issues (#3518)
5. [x] Verify previously-existing email when using a social account (#3728)
6. [x] Sync-up email addresses when editing users (#3737)

Also depends on:
* [x] Must be able to disable user sign ups (#3449)
* [x] CSRF cookie might be missing in private browsing sessions (#3774)

### PR DESCRIPTION
**Pull request by julen**
This PR introduces the allauth-based authentication backend, and implements the new workflow and UI for it.

Fixes #3343, #3515, #3517, #3518, #3728, #3737, #3774.

**IMPORTANT NOTES**
* It's **highly suggested** to migrate existing users to Allauth's own way to manage email addresses.
* The commit messages have issue references with stripped `#`s to avoid spam. They'll be brought back to normal immediately before merging happens.
* The PR doesn't cover:
  * Email management (add/change/remove addresses)
  * Explicit account linking/unlinking features

## Workflow testing

Before testing, ensure you are up-to-date with npm dependencies (`npm install` within *pootle/static/js*) and make sure to build JS modules (`manage.py webpack --dev`).

An outline of possible tests of the workflow follows. Added to this, triggering form validation errors anywhere in the process can help too.

1. Sign In
  * Confirmed user (signed up, verified email address)
     * signs user in
        * redirects to
          * previous URL in case `next` was specified
          * `settings.LOGIN_URL` otherwise
  * Unconfirmed user (signed up, didn't verify email address yet)
    * re-sends activation email
    * re-check this after a cooling down period of a few minutes; prevents impatient users from being bombarded with emails
  * Unconfirmed user (existed prior to allauth, didn't verify email address in allauth) — *this should ideally be avoided by migrating users' data*
    * sends activation email
    * click email link to verify email and confirm user account
  * Inactive user (admin deactivated user, `is_active = False`)
    * trying to sign in will display the inactive screen
2. Sign Up
  * Provide new user data
    * sends activation email
  * Click email link to verify email and confirm user account
    * signs user automatically in
    * redirects to `settings.LOGIN_REDIRECT_URL`
3. Password Reset
  * Request password reset
    * sends reset link in an email
  * Click reset link in the email
    * reset password
      * resets password and signs user in, redirecting to `/` (unfortunately cannot redirect to `settings.LOGIN_REDIRECT_URL` due to allauth's limitation)
    * sign out
    * sign in with new password
  * Open invalid/outdated/already-reset password reset link
    * displays message of invalid reset link

If you feel brave you can also test some social authentication provider (just enable a provider by adding it to `INSTALLED_APPS`; it'll show up), but note that that area hasn't been fully addressed yet so YMMV.

### CODE REVIEW

**Comment by dwaynebailey** [comment]
Did a test install and tested, didn't review the actual code.  Bullets in no particular order:

* "Sign In With..." header on Sign in popup - it is odd to see 'With...' when you only have one option. It makes sense when there are multiple signup methods.  But when there is one it just seems odd.
* ``initdb`` - default admin user is blocked as it needs email verification, we should by default have a working admin user after initdb.  Admin has no email address so that could be a problem with allauth.
* Reset password.  If passwords are different the button is enabled.  If you reset with different passwords then we stay on the page.
* Login/Logout - the process is long, and no indication that we're waiting for it complete.
* Forgotten password - sticks on the email page, we don't get to p6.5 and p7
  * Email and link arrive and is clicked on
  * Resetting password got stuck on the password reset page
  * This causes the whole site to lock
  * Forcing the reload of another page and we seem to be working again and the password is reset.

**Comment by jleclanche** [comment]
> Reset password. If passwords are different the button is enabled. If you reset with different passwords then we stay on the page.

I don't understand?

**Comment by dwaynebailey** [comment]
@julen finished my review

**Comment by julen** [comment]
Thanks for the extensive review, @dwaynebailey!

I have pushed an update to the PR, which include:
* Rebased against master, which has fixes for #3607 and #3622. These two were affecting your testing as confirmed on IRC. If you further experience either a screen that does nothing/freezes, or some page being displayed briefly when following a link, that's a bug.
* The *Sign In With...* header now adapts to *Sign In*.
* Visual adjustments for email addresses and text.
* A message is displayed once sign in has been successful but we are waiting to be redirected.

Besides that, and reading your feedback, it's worth noting that generally speaking,
* It might not be obvious at first, but allauth differentiates between unverified and inactive users. The former is allauth's own way to tell whether users have verified their email address or not, whereas the latter is `User` model's flag to disable a user entirely — its semantics are not altered so admins can permanently block users. I've got the impression you confused these two.
* Resending activation buttons are not necessary [as outlined in a previous comment](https://github.com/translate/pootle/issues/3517#issuecomment-74875092).

Re. `initdb`, feel free to propose any necessary code changes; it's essentially up to you whether you want to force to input a valid email via `createsuperuser` or use a fake email address (note in this case email-based workflows will be *broken*). In any scenario you'll need to create an entry for allauth's `EmailAddress` model with `verified=True`, as it keeps track of them as separate entities.

**Comment by dwaynebailey** [comment]
@julen started to test socialauth.  The difficult part is that we need Django Admin accessible to setup the Client ID and secret key. How would I do that?

**Comment by julen** [comment]
We didn't have the need to do so because of the nature of our own provider.

While django admin can be added by any custom install, it still requires to hook in the urlconf. Personally I wouldn't be comfortable to pull django admin because of this... but I'm afraid I don't have a specific answer on the matter.

**Comment by dwaynebailey** [comment]
@translate/core if you want to test socialauth the best is to follow these [instructions](http://www.sarahhagstrom.com/2013/09/the-missing-django-allauth-tutorial/).  They use SQL instead of Django Admin to set things up.  I guess that is what we should advise admins.  I used GitHub which was pretty easy, just [register](https://github.com/settings/applications/new) your app against localhost:8000.

**Github fields**
Application name: whatever you want
Homepage URL: http://localhost:8000
Application description: whatever you want
Authorization callback URL: http://127.0.0.1:8000/accounts/github/login/callback/

**SQL for the above**
```sql
UPDATE django_site SET DOMAIN = '127.0.0.1:8000', name = 'Pootle' WHERE id=1;
INSERT INTO socialaccount_socialapp (provider, name, secret, client_id, `key`)
 VALUES ("github", "GitHub", "---Client-Secret-from-above---",
 "---Client-ID-from-abive---", "");
INSERT INTO socialaccount_socialapp_sites (socialapp_id, site_id) VALUES (1,1);
```

I'm sure you can follow similar things with other Social Auth backends.

**Comment by julen** [comment]
This is now complete, waiting for :bug:s, there have to be many :smiley:

**Comment by julen** [comment]
Forgot to mention that I still want to look at polishing some of the UI interactions, especially when it comes to providing feedback to the user.

**Comment by ta2-1** [comment]
does behavior on `/accounts/password/change/`page relate to this PR?
It has changed my password without any notification.

**Comment by ta2-1** [comment]
I didn't received any notification as "password has been changed successfully" after I changed my password by the reset-password link. Is it ok?

**Comment by julen** [comment]
> I didn't received any notification as "password has been changed successfully" after I changed my password by the reset-password link. Is it ok?

If you're referring to an email notification no, there's none. Other than that, UI-wise we haven't invested in this feature, and there are no regressions AFAICT.

**Comment by ta2-1** [comment]
@julen I meant here https://github.com/translate/pootle/pull/3667#issuecomment-103007533 that old password change page is still avalable in http://pootle.server/accounts/password/change/. We discussed that a password can be changed via reset-link only.

**Comment by julen** [comment]
> We discussed that a password can be changed via reset-link only.

Can you give me a pointer? I'm not aware of anything like this.

Also, password change is not covered in this PR besides simply replacing `django.contrib.auth`'s password change views with Allauth's owns.

**Comment by dwaynebailey** [comment]
@julen complete a high level review again of normal allauth i.e. not socialauth.

## General issues
I don't see any as critical to fix.

- If email backend is on SMTP and it doesn't work then we block on login i.e no
  failure.  Not sure what correct failure would be for a user.
- Shouldn't we just use the change password popup instead of what we have on
  Settings->Password. Or just drop that and make all password changes need to happen on the login popup.
- Can't create a user without a password - future feature to be able to create
  a user that the user needs to verify and set a password.  Its a bit odd being
  an admin and setting the password.

# Worked

- Created a superuser - worked
- Got verification email and then logged in - worked
- Changed password from users settings page -worked
- Signout - worked
- Reset password via email - worked
- Created a new user through the UI - worked

**Comment by dwaynebailey** [comment]
@julen here are my notes from social auth testing

## Social auth

- It's still a struggle to setup easily - but my instructions helped
- I used Github auth
- This [traceback](https://dpaste.de/zFw9) -- MultipleObjectsReturned: get() returned more than one User -- it returned 4! -- was fixed and verified.

- Tried normal login after failure above
  - Got a weird mangled error over the popup but logged in - I wouldn't worry about that.

- Faked around the 4 blank emails by giving them all addresses

- Logged in with social auth
  - http://localhost:8000/accounts/social/signup/ - this page is unstyle, seems its not handled by our workflow
    - I guess then we need to be clear in the release notes that deployments will need to style pages themselves if they're using social auth.
  - Do we really need the "Are you human page" after signin with Github?  I'd say no since we have already authenticated via the social auth.
  - http://localhost:8000/accounts/password/set/ - now also unstyled.  Is this setting a password on Pootle or Github?

- If I log in to Github but already have a user with that email on Pootle
  - I get a rejection that says I should login first then link accounts
  - I login
  - But then have no way to link the account
  - Works fine if I associate it with a new email, don't need to validate either,

- If I'm on the admin page there is now way to know that a user is linked to  social auth in any way.

## Issues

1. Difficulty in setup/setup instructions needed
2. Unstyled pages need styling or release note/docs mention.
3. Linking account isn't present
4. No indication on user admin page of any links between accounts and social auth.

**Comment by dwaynebailey** [comment]
@julen from a normal auth perspective this is :+1: 

For social auth there are some issues which we handle in ``master`` and/or documenting the limitation in the docs and release notes.

If  social auth is :+1: for Evernote then I think lets land this baby.

**Comment by julen** [comment]
> * If email backend is on SMTP and it doesn't work then we block on login i.e no failure. Not sure what correct failure would be for a user.

Does it result in an unhandled traceback?

> * Shouldn't we just use the change password popup instead of what we have on Settings->Password. Or just drop that and make all password changes need to happen on the login popup.

I'm fine with whatever provided there's agreement.

> * Can't create a user without a password - future feature to be able to create a user that the user needs to verify and set a password. Its a bit odd being an admin and setting the password

While somehow valid, this is admin/users responsibility and it has always been the case, hence it's unrelated to this PR.

**Comment by julen** [comment]
>     1. Difficulty in setup/setup instructions needed

I reference here [a previous comment of mine](https://github.com/translate/pootle/pull/3667#issuecomment-99758994). Feel free to propose any patches on allauth to offer an alternative (CL) interface to manage/add social app instances.

>    2. Unstyled pages need styling or release note/docs mention.

The workflow that we aim to support and cover is completely styled — the pages you mention don't fall in there. If you want/plan to support extra workflows, you can work on that separately (unless you think it's a blocker).

>    3. Linking account isn't present

In the workflow we have implemented, linking happens when someone tries to sign in using an account that reports an email that already exists on the system.

There's #3553 for providing an explicit UI for such, although @iafan might argue this is not necessary. Let any related discussion happen over there.

>     No indication on user admin page of any links between accounts and social auth.

Also, while nice to have, I believe this falls out of the scope of what we're trying to provide here.

**Comment by dwaynebailey** [comment]
>
>
>    - Shouldn't we just use the change password popup instead of what we
>    have on Settings->Password. Or just drop that and make all password changes
>    need to happen on the login popup.
>
>  I'm fine with whatever provided there's agreement.
>
I'm trying not to scope creep here.  So I'm happy to leave this out of it.

My choices would be to expose the JS allauth password change popup that is
part of the existing workflow.

I'd like to hear @iafan's views on this item.


>
>    - Can't create a user without a password - future feature to be able
>    to create a user that the user needs to verify and set a password. Its a
>    bit odd being an admin and setting the password
>
>  While somehow valid, this is admin/users responsibility and it has
> always been the case, hence it's unrelated to this PR.
>

Agreed, not in scope


-- 
Dwayne

*Translate*
+27 12 460 1095 (work)

**Comment by dwaynebailey** [comment]
> 1. Difficulty in setup/setup instructions needed
>
>  I reference here a previous comment of mine
> <https://github.com/translate/pootle/pull/3667#issuecomment-99758994>.
> Feel free to propose any patches on allauth to offer an alternative (CL)
> interface to manage/add social app instances.
>

My current concern is not social auth so we won't be looking at simpler
models to solve that now.  My concern is that there are at least some notes
to guide someone who wants to use it.  Those are dramatically missing at
the moment.


>
>    1. Unstyled pages need styling or release note/docs mention.
>
>  The workflow that we aim to support and cover is completely styled — the
> pages you mention don't fall in there. If you want/plan to support extra
> workflows, you can work on that separately (unless you think it's a
> blocker).
>
Social auth isn't a blocker for me.  I would appreciate some pointers as to
where and how that would be styled in the same way that it is a concern
around setup.

We can slowly add those missing pages as required later.



>
>    1. Linking account isn't present
>
>  In the workflow we have implemented, linking happens when someone tries
> to sign in using an account that reports an email that already exists on
> the system.
>
> There's #3553 <https://github.com/translate/pootle/issues/3553> for
> providing an explicit UI for such, although @iafan
> <https://github.com/iafan> might argue this is not necessary. Let any
> related discussion happen over there.
>
> No indication on user admin page of any links between accounts and social auth.
>
>  Also, while nice to have, I believe this falls out of the scope of what
> we're trying to provide here.
>
I'm happy to agree this is not in this scope.  And can be dealt with
elsewhere.


-- 
Dwayne

*Translate*
+27 12 460 1095 (work)

**Comment by julen** [comment]
>>> 1. Unstyled pages need styling or release note/docs mention.
>>
>>  The workflow that we aim to support and cover is completely styled — the
>>  pages you mention don't fall in there. If you want/plan to support extra
>>  workflows, you can work on that separately (unless you think it's a
>>  blocker).
>
> Social auth isn't a blocker for me.  I would appreciate some pointers as to
> where and how that would be styled in the same way that it is a concern
> around setup.

Not sure I get your point, but I'm afraid you cannot set some flag and have that workflow *automagically* supported in the code unless you actually implement the views client-side. Of course, you can create templates for the workflow views that this PR doesn't intend to support, therefore accommodating to Pootle's layout/look, but the offered UX will be average.

**Comment by dwaynebailey** [comment]
@julen so if I hear you right.  Its not a matter of missing templates (although they are missing) but rather that that part of e.g. a Github workflow would need to be implemented in JS code?

**Comment by julen** [comment]
Let's put it this way: the client-side code in the PR doesn't cover anything that falls out of the screens you see in the mockups (I can only think of a situation where it'd be possible to hit such scenario, which is using a provider that doesn't provide an email address; or not requiring an email address at all).

If you guys are willing to support alternative workflow steps while preserving the UX, this needs to be implemented client-side obviously. The alternative option is just including templates, but that results in an inconsistent UX.

**Comment by ta2-1** [comment]
@julen I'm not able to login with existing user and password when Chrome incognito mode is enabled.
I got this:
```
Failed to load resource: https://translate.stage.evernote.com/accounts/login/?next=%2F 
the server responded with a status of 403 (FORBIDDEN)
```

**Comment by julen** [comment]
Right, @jleclanche already reported that on IRC a while ago which I forgot about — filed #3774.

**Comment by ta2-1** [comment]
It's allowed to change user email in admin UI.
I set the same email for two different users. Then I set the same email to EN user. Then I tried to sign in with EN, then reset password and... got two different reset password links.

**Comment by julen** [comment]
Could you explain the steps to reproduce that? It's unclear if you signed in at all and therefore in which context you requested to reset your password.

Also, what is specifically an *EN user* and its email?
Accidents aside, why would you want to set the same email to two different users?

**Comment by ta2-1** [comment]
@julen it doesn't make sense to set the same email to two users. 
But it's possible.
How is a linked row in `account_emailaddress` changed if I change user email? I suspect that we don't touch it. Do we have unique constraint on email field there?
I tested how social auth works with such duplicated emails if some uncovered case can be caught.
If we address this constraint I believe the case I described can't be reproduced.

**Comment by jleclanche** [comment]
`ACCOUNT_UNIQUE_EMAIL` is set to True by default: https://django-allauth.readthedocs.org/en/latest/configuration.html

**Comment by julen** [comment]
We quickly discussed this and everything boils down to #3737.

**Pull request merged**
