### PR TITLE
Editor: Don't update total units count when fetching more units

### LINKED ISSUE #4640: Wrong unit numbering while translating
While translating on MLO (which I assume is running something around current master), I experienced an odd unit numbering behavior in the editor: I could go further beyond the maximum number of units reported for my current filter (_incomplete_).

editor_total_count_bug

### PR DESCRIPTION
**Pull request by unho**
Fixes #4640.

### CODE REVIEW

**Comment by julen** [comment]
Thank you, @unho! I haven't tested  the PR (and won't be able to verify it until I'm back), although I quickly checked the code and part of me feels it unnecessarily complicates UI code.

Wouldn't it be better to keep a copy of the value of `total` frozen unless a new `initial` request is made? In case the updated value of `total` is needed to calculate batches/offsets, having the frozen value in a separate property should be enough (something like `this.units.frozenTotal`), and it would help in keeping the UI code simpler, as it would always display the value of `frozenTotal`.

**Comment by unho** [comment]
@julen Updated. I hope this is what you were talking about.

**Comment by phlax** [comment]
lgtm - nice one @unho

**Comment by unho** [comment]
@julen Merged this since we are pretty sure it fixes the issue the way you suggested.

**Comment by julen** [comment]
@unho well done, verified 👍

**Pull request merged**
