### PR TITLE
Drop some EN specific customisations

### PR DESCRIPTION
**Pull request by dwaynebailey**
Some things I picked up in LO deployment.  PR'ing so that @translate/evernote are aware of changes needed to templates on your deployment.

- First drops the 'English' contact requirements - deployment specific
- Second - I know this should go with allauth - while allauth hasn't landed this functionality should be gone and this allows us to extend this as needed in future.

### CODE REVIEW

**Comment by julen** [comment]
The first one is ok, leave out the second one please, it's gone in the allauth branch.

**Comment by unho** [comment]
I don't think anyone managing a Pootle server with more than a few languages is capable of  understand feedback written in any language. That is the reason behind the request to write in English. I think we must keep that as the default, and allow to overextend to accept other languages in custom installs.

**Comment by jleclanche** [comment]
Let's not impose "write in english" on everyone, the condition doesn't need to be mentioned either way.

**Comment by jleclanche** [comment]
gtm per julen's instructions

**Pull request merged**
